apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-adr-test
  annotations:
    github.com/project-slug: NicklasFranzen/backstage-adr-test
spec:
  type: other
  lifecycle: unknown
  owner: Nisse
